# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/btmainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 379)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.device_label = QtWidgets.QLabel(self.centralwidget)
        self.device_label.setGeometry(QtCore.QRect(20, 70, 331, 22))
        self.device_label.setObjectName("device_label")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(390, 70, 67, 21))
        self.status_label.setObjectName("status_label")
        self.power_button = QtWidgets.QPushButton(self.centralwidget)
        self.power_button.setGeometry(QtCore.QRect(20, 10, 99, 38))
        self.power_button.setObjectName("power_button")
        self.devices_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.devices_combo_box.setGeometry(QtCore.QRect(20, 120, 331, 36))
        self.devices_combo_box.setObjectName("devices_combo_box")
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(380, 120, 99, 38))
        self.connect_button.setObjectName("connect_button")
        self.power_label = QtWidgets.QLabel(self.centralwidget)
        self.power_label.setGeometry(QtCore.QRect(140, 10, 67, 31))
        font = QtGui.QFont()
        font.setFamily("UbuntuMono Nerd Font")
        font.setPointSize(13)
        font.setItalic(True)
        self.power_label.setFont(font)
        self.power_label.setObjectName("power_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 616, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.device_label.setText(_translate("MainWindow", "DevName"))
        self.status_label.setText(_translate("MainWindow", "Status: "))
        self.power_button.setText(_translate("MainWindow", "Power"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.power_label.setText(_translate("MainWindow", " Off "))
